#!/usr/bin/env python

# Used to store the last mapped point cloud
import rospy
from sensor_msgs.msg import PointCloud2, Image
import numpy as np
import sys
import rospkg

lastCloud = None

def saveCloud(self,data):
    global lastcloud
    self.lastcloud = data

def mappingToggle(self,data):
    if data.data=="off":
        if self.lastcloud is not None:
            rospack = rospkg.RosPack()
            path = rospack.get_path('drone_panda')+'/saved_msgs/pc_new.txt'
            with open(path, 'w') as outfile:
                self.lastcloud.serialize(outfile.buffer)


def getPC():
    rospy.init_node('pc_recorder')
    print("reading")
    msg = PointCloud2()
    rospack = rospkg.RosPack()
    rospy.Subscriber("/rtabmap/cloud_map",PointCloud2,saveCloud)
    rospy.Subscriber("mappingToggle", String, mappingToggle)
    rospy.spin()


if __name__ == '__main__':
    getPC()


